import type { nav_content as _nav_content } from "../navbar";

export const nav_content: _nav_content = {
  merge: "دمج",
  split: "تقسيم",
  compress: "ضغط",
  edit: {
    title: "تحرير",
    read: "قراءة PDF",
    edit: "تحرير PDF",
    number: "ترقيم PDF",
    rotate: "تدوير PDF",
    lock: "قفل PDF",
    unlock: "إلغاء قفل PDF",
    watermark: "علامة مائية للـ PDF",
    remove: "إزالة الصفحات",
  },
  convert: "تحويل",
  convert_pdf: "تحويل PDF",
  read_edit_pdf: "قراءة وتحرير PDF",
  convert_to_pdf: "تحويل إلى PDF",
  convert_to: {
    jpg_to_pdf: "JPG إلى PDF",
    png_to_pdf: "PNG إلى PDF",
    gif_to_pdf: "GIF إلى PDF",
    tiff_to_pdf: "TIFF إلى PDF",
    bmp_to_pdf: "BMP إلى PDF",
    svg_to_pdf: "SVG إلى PDF",
    webp_to_pdf: "WebP إلى PDF",
    heif_heic_to_pdf: "تحويل HEIF/HEIC إلى PDF",
    word_to_pdf: "Word إلى PDF",
    powerpoint_to_pdf: "PowerPoint إلى PDF",
    excel_to_pdf: "Excel إلى PDF",
    html_to_pdf: "HTML إلى PDF",
    markdown_to_pdf: "Markdown إلى PDF",
    web_to_pdf: "من الويب إلى PDF",
  },
  convert_from_pdf: "تحويل من PDF",
  convert_from: {
    pdf_to_jpg: "PDF إلى JPG",
    pdf_to_word: "PDF إلى Word",
    pdf_to_powerpoint: "PDF إلى PowerPoint",
    pdf_to_excel: "PDF إلى Excel",
    pdf_to_pdf_a: "PDF إلى PDF/A",
    pdf_to_text: "PDF إلى نص",
    pdf_to_html: "PDF إلى HTML",
    pdf_to_markdown: "PDF إلى Markdown",
    pdf_to_png: "PDF إلى PNG",
    pdf_to_gif: "PDF إلى GIF",
    pdf_to_tiff: "PDF إلى TIFF",
    pdf_to_bmp: "PDF إلى BMP",
    pdf_to_svg: "PDF إلى SVG",
    pdf_to_webp: "PDF إلى WebP",
    pdf_to_heif_heic: "PDF إلى HEIF/HEIC"
  },
  sidebar: { menu: "القائمة", home: "الصفحة الرئيسية" },
  language: "اللغة"

};
