export const nav_content = {
  merge: "Merge",
  split: "Split",
  compress: "Compress",
  convert_pdf: "Convert PDF",
  convert: "Convert",
  convert_to_pdf: "Convert to PDF",
  edit: {
    title: "Edit",
    read: "Read PDF",
    edit: "Edit PDF",
    number: "Number PDF",
    rotate: "Rotate PDF",
    lock: "Lock PDF",
    unlock: "Unlock PDF",
    watermark: "Watermark PDF",
    remove: "Remove Pages"
  },
  convert_from: {
    pdf_to_jpg: "PDF to JPG",
    pdf_to_word: "PDF to WORD",
    pdf_to_powerpoint: "PDF to POWERPOINT",
    pdf_to_excel: "PDF to EXCEL",
    pdf_to_text: "PDF to text",
    pdf_to_html: "PDF to HTML",
    pdf_to_markdown: "PDF to Markdown",
    pdf_to_pdf_a: "PDF to PDF/A",
    pdf_to_png: "PDF to PNG",
    pdf_to_gif: "PDF to GIF",
    pdf_to_tiff: "PDF to TIFF",
    pdf_to_bmp: "PDF to BMP",
    pdf_to_svg: "PDF to SVG",
    pdf_to_webp: "PDF to WebP",
    pdf_to_heif_heic: "PDF to HEIF/HEIC",
  },
  convert_from_pdf: "Convert from PDF",
  read_edit_pdf: "Read & Edit PDF",
  convert_to: {
    jpg_to_pdf: "JPG to PDF",
    png_to_pdf: "PNG to PDF",
    gif_to_pdf: "GIF to PDF",
    tiff_to_pdf: "TIFF to PDF",
    bmp_to_pdf: "BMP to PDF",
    svg_to_pdf: "SVG to PDF",
    webp_to_pdf: "WebP to PDF",
    heif_heic_to_pdf: "HEIF/HEIC to PDF",
    word_to_pdf: "WORD to PDF",
    powerpoint_to_pdf: "POWERPOINT to PDF",
    excel_to_pdf: "EXCEL to PDF",
    html_to_pdf: "HTML to PDF",
    web_to_pdf: "Web to PDF",
    markdown_to_pdf: "Markdown to PDF",
  },
  sidebar: { menu: "Menu", home: "Home" },
  language: "Language"
};
