import type { nav_content as _nav_content } from "../navbar";

export const nav_content: _nav_content = {
  merge: "Combinar",
  split: "Dividir",
  compress: "Comprimir",
  edit: {
    title: "Editar",
    read: "Leer PDF",
    edit: "Editar PDF",
    number: "Numerar PDF",
    rotate: "Rotar PDF",
    lock: "Bloquear PDF",
    unlock: "Desbloquear PDF",
    watermark: "Marca de agua en PDF",
    remove: "Eliminar Página"
  },
  convert: "Convertir",
  convert_pdf: "Convertir PDF",
  convert_from_pdf: "Convertir desde PDF",
  read_edit_pdf: "Leer y editar PDF",
  convert_to_pdf: "Convertir a PDF",
  convert_to: {
    jpg_to_pdf: "JPG a PDF",
    png_to_pdf: "PNG a PDF",
    gif_to_pdf: "GIF a PDF",
    tiff_to_pdf: "TIFF a PDF",
    bmp_to_pdf: "BMP a PDF",
    svg_to_pdf: "SVG a PDF",
    webp_to_pdf: "WebP a PDF",
    heif_heic_to_pdf: "HEIF/HEIC a PDF",
    word_to_pdf: "Word a PDF",
    powerpoint_to_pdf: "Powerpoint a PDF",
    excel_to_pdf: "Excel a PDF",
    html_to_pdf: "HTML a PDF",
    markdown_to_pdf: "Markdown a PDF",
    web_to_pdf: "Web a PDF",
  },
  convert_from: {
    pdf_to_jpg: "PDF a JPG",
    pdf_to_word: "PDF a Word",
    pdf_to_powerpoint: "PDF a Powerpoint",
    pdf_to_excel: "PDF a Excel",
    pdf_to_pdf_a: "PDF a PDF/A",
    pdf_to_text: "PDF a texto",
    pdf_to_html: "PDF a HTML",
    pdf_to_markdown: "PDF a Markdown",
    pdf_to_png: "PDF a PNG",
    pdf_to_gif: "PDF a GIF",
    pdf_to_tiff: "PDF a TIFF",
    pdf_to_bmp: "PDF a BMP",
    pdf_to_svg: "PDF a SVG",
    pdf_to_webp: "PDF a WebP",
    pdf_to_heif_heic: "PDF a HEIF/HEIC"
  },
  sidebar: { menu: "Menú", home: "Inicio" },
  language: "Idioma"
};
