import type { nav_content as _nav_content } from "../navbar";

export const nav_content: _nav_content = {
  merge: "Fusionner",
  split: "Diviser",
  compress: "Compresser",
  edit: {
    title: "Modifier",
    read: "Lire le PDF",
    edit: "Modifier le PDF",
    number: "Numéroter le PDF",
    rotate: "Faire pivoter le PDF",
    lock: "Verrouiller le PDF",
    unlock: "Déverrouiller le PDF",
    watermark: "Filigrane PDF",
    remove: "Supprimer les pages"
  },
  convert: "Convertir",
  convert_pdf: "Convertir des PDF",
  convert_to_pdf: "Convertir en PDF",
  convert_from_pdf: "Convertir à partir de PDF",
  read_edit_pdf: "Lire et modifier un PDF",
  convert_to: {
    jpg_to_pdf: "JPG en PDF",
    png_to_pdf: "PNG en PDF",
    gif_to_pdf: "GIF en PDF",
    tiff_to_pdf: "TIFF en PDF",
    bmp_to_pdf: "BMP en PDF",
    svg_to_pdf: "SVG en PDF",
    webp_to_pdf: "WebP en PDF",
    heif_heic_to_pdf: "HEIF/HEIC vers PDF",
    word_to_pdf: "WORD en PDF",
    powerpoint_to_pdf: "POWERPOINT en PDF",
    excel_to_pdf: "EXCEL en PDF",
    html_to_pdf: "HTML en PDF",
    markdown_to_pdf: "Markdown en PDF",
    web_to_pdf: "Web vers PDF",
  },
  convert_from: {
    pdf_to_jpg: "PDF en JPG",
    pdf_to_word: "PDF en WORD",
    pdf_to_powerpoint: "PDF en POWERPOINT",
    pdf_to_excel: "PDF en EXCEL",
    pdf_to_pdf_a: "PDF en PDF/A",
    pdf_to_text: "PDF en texte",
    pdf_to_html: "PDF vers HTML",
    pdf_to_markdown: "PDF à Markdown",
    pdf_to_png: "PDF vers PNG",
    pdf_to_gif: "PDF vers GIF",
    pdf_to_tiff: "PDF vers TIFF",
    pdf_to_bmp: "PDF vers BMP",
    pdf_to_svg: "PDF vers SVG",
    pdf_to_webp: "PDF vers WebP",
    pdf_to_heif_heic: "PDF vers HEIF/HEIC"
  },
  sidebar: { menu: "Menu", home: "Accueil" },
  language: "Langue"
};
