import type { nav_content as _nav_content } from "../navbar";

export const nav_content: _nav_content = {
  merge: "मर्ज",
  split: "विभाजित",
  compress: "संपीड़ित",
  convert_pdf: "पीडीएफ परिवर्तित करें",
  edit: {
    title: "संपादित करें",
    read: "पीडीएफ पढ़ें",
    edit: "पीडीएफ संपादित करें",
    number: "पीडीएफ को नंबर करें",
    rotate: "पीडीएफ को घुमाएं",
    lock: "पीडीएफ को ताला लगाएं",
    unlock: "पीडीएफ का ताला खोलें",
    watermark: "पीडीएफ पर जलीय चिह्न",
    remove: "पृष्ठ हटाएं"
  },
  convert: "रूपांतरित करें",
  convert_to_pdf: "पीडीएफ में परिवर्तित करें",
  convert_from_pdf: "पीडीएफ से परिवर्तित करें",
  read_edit_pdf: "पीडीएफ पढ़ें और संपादित करें",
  convert_to: {
    jpg_to_pdf: "जेपीजी से पीडीएफ",
    png_to_pdf: "पीएनजी से पीडीएफ",
    gif_to_pdf: "जीआईएफ से पीडीएफ",
    tiff_to_pdf: "टिफ से पीडीएफ",
    bmp_to_pdf: "बीएमपी से पीडीएफ",
    svg_to_pdf: "एसवीजी से पीडीएफ",
    webp_to_pdf: "वेबपी से पीडीएफ",
    heif_heic_to_pdf: "HEIF/HEIC से PDF",
    word_to_pdf: "शब्द से पीडीएफ",
    powerpoint_to_pdf: "पावरपॉइंट से पीडीएफ",
    excel_to_pdf: "एक्सेल से पीडीएफ",
    html_to_pdf: "एचटीएमएल से पीडीएफ",
    markdown_to_pdf: "पीडीएफ में मार्कडाउन करें",
    web_to_pdf: "वेब से पीडीएफ",
  },
  convert_from: {
    pdf_to_jpg: "पीडीएफ से जेपीजी",
    pdf_to_word: "पीडीएफ से शब्द",
    pdf_to_powerpoint: "पीडीएफ से पावरपॉइंट",
    pdf_to_excel: "पीडीएफ से एक्सेल",
    pdf_to_pdf_a: "पीडीएफ से पीडीएफ/ए",
    pdf_to_text: "पाठ के लिए पीडीएफ",
    pdf_to_html: "पीडीएफ से एचटीएमएल",
    pdf_to_markdown: "PDF से मार्कडाउन तक",
    pdf_to_png: "पीडीएफ से पीएनजी में",
    pdf_to_gif: "पीडीएफ से जीआईएफ में",
    pdf_to_tiff: "पीडीएफ से टिफ़ में",
    pdf_to_bmp: "पीडीएफ से बीएमपी में",
    pdf_to_svg: "पीडीएफ से एसवीजी में",
    pdf_to_webp: "पीडीएफ से वेबपी में",
    pdf_to_heif_heic: "पीडीएफ से हीइएफ/हीइक में"
  },
  sidebar: { menu: "मेनू", home: "होम" },
  language: "भाषा"
};
